# Web_Scraping_Assignment 3 Solution

In [1]:
#import necessary libraries
import selenium
import time
import pandas as pd
from selenium import webdriver

In [2]:
#Setting up firefox web-driver
driver = webdriver.Firefox(executable_path = 'geckodriver.exe')

# Q1 Write a python program which searches all the product under a particular product verticalfrom www.amazon.in. The product verticals to be searched will be taken as input from user.

In [31]:
#Importing URL
page1 = driver.get('https://www.amazon.in/')

In [32]:
#Send keys to product search
product = driver.find_element_by_id('twotabsearchtextbox')
product.send_keys('Tablets')
time.sleep(2)
btn = driver.find_element_by_id('nav-search-submit-button')
btn.click()

#  Q.2

In [33]:
product = driver.find_elements_by_xpath('//h2[@class="a-size-mini a-spacing-none a-color-base s-line-clamp-2"]')
price = driver.find_elements_by_xpath('//span[@class="a-price-whole"]')
product_url = driver.find_elements_by_xpath('//a[@class="a-link-normal a-text-normal"]')

In [34]:
Product = []#empty List
Price = []#empty List
Product_url = []#empty List


for i in product:
    Product.append(i.text)#scraping product
time.sleep(2)
for i in price:
    Price.append(i.text)#scraping price
time.sleep(2)
for i in product_url:
    Product_url.append(i.get_attribute('href'))#scraping product_url
time.sleep(2)

In [35]:
page_url = []#empty List
url = driver.find_elements_by_xpath('//li[@class="a-normal"]//a')

for i in url:
    page_url.append(i.get_attribute('href'))

In [36]:
Brand = []#empty List
Rating = []#empty List
No_of_Rating = []#empty List
Delivery = []#empty List
Return = []#empty List
Availability = []#empty List

for i in Product_url:
    driver.get(i)
    time.sleep(2)
    try:
        brand = driver.find_element_by_xpath('//*[@id="productOverview_feature_div"]/div/table/tbody/tr[2]/td[2]/span')
        Brand.append(brand.text)
    except:
        Brand.append('-')
        time.sleep(2)
    try:
        rating = driver.find_element_by_xpath('//*[@id="acrPopover"]/span[1]/a/i[1]/span')
        Rating.append(rating.text)#Scraping ratings
    except:
        Rating.append('-')
        time.sleep(2)
    try:
        no_rating = driver.find_element_by_xpath('//*[@id="acrCustomerReviewText"]')
        No_of_Rating.append(no_rating.text.replace('ratings',''))#Scraping no of Ratings
    except:
        No_of_Rating.append('-')
        time.sleep(2)
    try:
        delivery = driver.find_element_by_xpath('//*[@id="ddmDeliveryMessage"]/b')
        Delivery.append(delivery.text)#Scraping deliery time
    except:
        Delivery.append('-')
        time.sleep(2)
    try:
        exchange = driver.find_element_by_xpath('//*[@id="RETURNS_POLICY"]/span/div[2]/a')
        Return.append(exchange.text)#Scraping exchange time
    except:
        Return.append('-')
        time.sleep(2)
    try:
        available = driver.find_element_by_xpath('//*[@id="availability"]/span')
        Availability.append(available.text)#Scraping availability
    except:
        Availability.append('-')

In [38]:
for i in page_url:
    driver.get(i)
    product = driver.find_elements_by_xpath('//h2[@class="a-size-mini a-spacing-none a-color-base s-line-clamp-2"]')
    price = driver.find_elements_by_xpath('//span[@class="a-price-whole"]')
    product_url = driver.find_elements_by_xpath('//a[@class="a-link-normal a-text-normal"]')


    for i in product:
        Product.append(i.text)#scraping product
    time.sleep(2)
    for i in price:
        Price.append(i.text)#scraping price
    time.sleep(2)
    for i in product_url:
        Product_url.append(i.get_attribute('href'))#scraping product_url
    time.sleep(2)
            
    for i in Product_url:
        driver.get(i)
        time.sleep(2)
        try:
            brand = driver.find_element_by_xpath('//*[@id="productOverview_feature_div"]/div/table/tbody/tr[2]/td[2]/span')
            Brand.append(brand.text)
        except:
            Brand.append('-')
            time.sleep(2)
        try:
            rating = driver.find_element_by_xpath('//*[@id="acrPopover"]/span[1]/a/i[1]/span')
            Rating.append(rating.text)#Scraping ratings
        except:
            Rating.append('-')
            time.sleep(2)
        try:
            no_rating = driver.find_element_by_xpath('//*[@id="acrCustomerReviewText"]')
            No_of_Rating.append(no_rating.text.replace('ratings',''))#Scraping no of Ratings
        except:
            No_of_Rating.append('-')
            time.sleep(2)
        try:
            delivery = driver.find_element_by_xpath('//*[@id="ddmDeliveryMessage"]/b')
            Delivery.append(delivery.text)#Scraping deliery time
        except:
            Delivery.append('-')
            time.sleep(2)
        try:
            exchange = driver.find_element_by_xpath('//*[@id="RETURNS_POLICY"]/span/div[2]/a')
            Return.append(exchange.text)#Scraping exchange time
        except:
            Return.append('-')
            time.sleep(2)
        try:
            available = driver.find_element_by_xpath('//*[@id="availability"]/span')
            Availability.append(available.text)#Scraping availability
        except:
            Availability.append('-')

In [56]:
len(No_of_Rating)

197

In [62]:
dfl = pd.DataFrame() #Making dataframe
dfl['Brand'] = Brand 
dfl['Product Name'] = Product 
dfl['Price']  = Price 
dfl['Product_url'] = Product_url 
dfl['No_of_Rating'] = No_of_Rating 
dfl['Return'] = Return 
dfl['Delivery'] = Delivery 
dfl['Availability'] = Availability 
dfl['Rating'] = Rating 
dfl

,Brand,Product Name,Price,Product_url,No_of_Rating,Return,Delivery,Availability,Rating
0,Lenovo,Lenovo Tab M10 FHD Plus (2nd Gen) (10.3 inch/2...,"23,400",https://www.amazon.in/gp/slredirect/picassoRed...,547,7 Days Replacement,"Sunday, Aug 29",In stock.,
1,Lenovo,Lenovo Yoga Smart Tablet with The Google Assis...,"21,894",https://www.amazon.in/gp/slredirect/picassoRed...,"2,322",7 Days Replacement,"Tuesday, Aug 31",In stock.,
2,Lenovo,Lenovo Tab M10 FHD Plus Tablet (10.3-inch/26.1...,"20,999",https://www.amazon.in/Lenovo-Tab-M10-FHD-Plus/...,"7,923",7 Days Replacement,"Sunday, Aug 29",In stock.,
3,Lenovo,Lenovo Yoga Smart Tablet with The Google Assis...,"21,894",https://www.amazon.in/Lenovo-Yoga-Smart-Google...,"2,322",7 Days Replacement,"Tuesday, Aug 31",In stock.,
4,Panasonic,"Panasonic Tab 8 HD Tablet (20.32 cm (8 Inch), ...","11,999",https://www.amazon.in/Panasonic-Tablet-Wi-Fi-V...,"1,881",7 Days Replacement,"Sunday, Aug 29",In stock.,
...,...,...,...,...,...,...,...,...,...
82,Lenovo,I KALL N4 4G Dual Sim Smart Tablet (Black),"5,699",https://www.amazon.in/KALL-N4-Smart-Tablet-Bla...,4,7 Days Replacement,"Tuesday, Aug 31",Only 2 left in stock.,
83,IKALL,"Lenovo Tab4 8 Plus Tablet (8 inch, 64GB, Wi-Fi...","18,699",https://www.amazon.in/Lenovo-Tab4-Plus-Tablet-...,-,7 Days Replacement,"Wednesday, Sep 1",In stock.,-
84,Lenovo,Samsung Galaxy Tab S7+ 31.5 cm (12.4 inch) Sup...,"84,990",https://www.amazon.in/Samsung-Galaxy-AMOLED-Di...,"2,164",7 Days Replacement,"Sunday, Aug 29",In stock.,
85,Samsung,Samsung Galaxy Tab S6 Lite 26.31 cm (10.4 inch...,"6,499",https://www.amazon.in/Samsung-Galaxy-Lite-Wi-F...,131,7 Days Replacement,"Sunday, Aug 29",In stock.,
86,IKALL,"I KALL N3 Calling Tablet 4G Dual Sim (7 Inch, ...","6,189",https://www.amazon.in/gp/slredirect/picassoRed...,44,7 Days Replacement,"Tuesday, Aug 31",In stock.,

# Write a python program to access the search bar and search button on images.google.com and scrape 100 images each for keywords ‘fruits’, ‘cars’ and ‘Machine Learning’.

In [53]:
page2 = driver.get('https://images.google.com/?gws_rd=ssl')

In [54]:
search = driver.find_element_by_xpath('/html/body/div[2]/div[2]/div/form/div[1]/div[1]/div[1]/div/div[2]/input')
search.send_keys('fruits')
#Put input in search section
btn = driver.find_element_by_xpath('/html/body/div[2]/div[2]/div/form/div[1]/div[1]/div[1]/button/div')
btn.click() #clicking button

In [55]:
Fruit_Images = []#empty List

images = driver.find_elements_by_xpath('//img[@class="rg_i Q4LuWd"]')
time.sleep(3)
for i in images:
    Fruit_Images.append(i.get_attribute('src'))# Scraping images

In [56]:
Car_Images = []#empty List
driver.find_element_by_xpath('//*[@id="REsRA"]').clear()
driver.find_element_by_xpath('//*[@id="REsRA"]').send_keys('cars')
driver.find_element_by_xpath('//span[@class="n6h3Rc"]').click()

time.sleep(3)
images = driver.find_elements_by_xpath('//img[@class="rg_i Q4LuWd"]')
for i in images:
    Car_Images.append(i.get_attribute('src'))# Scraping images

In [61]:
ML_Images = []#empty List
driver.find_element_by_xpath('//*[@id="REsRA"]').clear()
driver.find_element_by_xpath('//*[@id="REsRA"]').send_keys('Machine Learning')
driver.find_element_by_xpath('//span[@class="n6h3Rc"]').click()

time.sleep(3)
images = driver.find_elements_by_xpath('//img[@class="rg_i Q4LuWd"]')
for i in images:
    ML_Images.append(i.get_attribute('src'))# Scraping images

In [76]:
df = pd.DataFrame()#making dataframe
df['Fruit_Images'] = Fruit_Images[:100]
df['Car_Images'] = Car_Images[:100]
df['ML_Images'] = ML_Images[:100]
df.head()

,Fruit_Images,Car_Images,ML_Images
0,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA..."
1,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
2,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
3,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA..."
4,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."

# Write a python program to search for a smartphone(e.g.: Oneplus Nord, pixel 4A, etc.) on www.flipkart.com and scrape following details for all the search results displayed on 1st page. Details to be scraped: “Brand Name”, “Smartphone name”, “Colour”, “RAM”, “Storage(ROM)”, “Primary Camera”, “Secondary Camera”, “Display Size”, “Display Resolution”, “Processor”, “Processor Cores”, “Battery Capacity”, “Price”, “Product URL”. Incase if any of the details is missing then replace it by “- “. Save your results in a dataframe and CSV.

In [75]:
page3 = driver.get('https://www.flipkart.com/')

In [77]:
search = driver.find_element_by_xpath('//*[@id="container"]/div/div[1]/div[1]/div[2]/div[2]/form/div/div/input')
search.send_keys('redmi 10 pro max')
#Put input in search section
btn = driver.find_element_by_xpath('/html/body/div[1]/div/div[1]/div[1]/div[2]/div[2]/form/div/button')
btn.click()#click button

In [78]:
#“Brand Name”, “Smartphone name”, “Colour”, “RAM”, “Storage(ROM)”, “Primary Camera”, “Secondary Camera” 
#“Display Size”, “Display Resolution”, “Processor”, “Processor Cores”, “Battery Capacity”, “Price”, “Product URL”

Product = []#empty List
Colour = []#empty List
Ram = []#empty List
Rom = []#empty List
PCamera = []#empty List
SCamera = []#empty List
DisplaySize = []#empty List
DisplayR = []#empty List
Processor = []#empty List
Core = []#empty List
Battery = []#empty List
Price = []#empty List

url = driver.find_elements_by_xpath('//a[@class="_1fQZEK"]')

for i in url:
    Product_url.append(i.get_attribute('href'))
    time.sleep(3) #Scraping product_url

for i in Product_url:
    driver.get(i)
    driver.find_element_by_xpath('//button[@class="_2KpZ6l _1FH0tX"]').click()
    try:
        product = driver.find_element_by_xpath('//*[@id="container"]/div/div[3]/div[1]/div[2]/div[8]/div[4]/div/div[2]/div[1]/div[1]/table/tbody/tr[3]/td[2]/ul/li')
        Product.append(product.text)#Scrape product name
    except:
        Product.append('-')
    time.sleep(3)
    try:
        colour = driver.find_element_by_xpath('/html/body/div[1]/div/div[3]/div[1]/div[2]/div[8]/div[4]/div/div[2]/div[1]/div[1]/table/tbody/tr[4]/td[2]/ul/li')
        Colour.append(colour.text)#Scrape product colour
    except:
        Colour.append('-')
    time.sleep(3)
    try:
        ram = driver.find_element_by_xpath('/html/body/div[1]/div/div[3]/div[1]/div[2]/div[8]/div[4]/div/div[2]/div[1]/div[4]/table/tbody/tr[2]/td[2]/ul/li')
        Ram.append(ram.text) #Scrape ram of the product
    except:
        Ram.append('-')
    time.sleep(3)
    try:
        rom = driver.find_element_by_xpath('/html/body/div[1]/div/div[3]/div[1]/div[2]/div[8]/div[4]/div/div[2]/div[1]/div[4]/table/tbody/tr[1]/td[2]/ul/li')
        Rom.append(rom.text) #Scrape ram of the product
    except:
        Rom.append('-')
    time.sleep(3)
    try:
        pcamera = driver.find_element_by_xpath('/html/body/div[1]/div/div[3]/div[1]/div[2]/div[8]/div[4]/div/div[2]/div[1]/div[5]/table/tbody/tr[2]/td[2]/ul/li')
        PCamera.append(pcamera.text) #Scrape camera of the product
    except:
        PCamera.append('-')
    time.sleep(2)
    try:
        scamera = driver.find_element_by_xpath('/html/body/div[1]/div/div[3]/div[1]/div[2]/div[8]/div[4]/div/div[2]/div[1]/div[5]/table/tbody/tr[5]/td[2]/ul/li')
        SCamera.append(scamera.text) #Scrape camera of the product
    except:
        SCamera.append('-')
    time.sleep(2)
    try:
        display = driver.find_element_by_xpath('/html/body/div[1]/div/div[3]/div[1]/div[2]/div[8]/div[4]/div/div[2]/div[1]/div[2]/table/tbody/tr[1]/td[2]/ul/li')
        DisplaySize.append(display.text) #Scrape display of the product
    except:
        DisplaySize.append('-')
    time.sleep(2)
    try:
        displayr = driver.find_element_by_xpath('/html/body/div[1]/div/div[3]/div[1]/div[2]/div[8]/div[4]/div/div[2]/div[1]/div[2]/table/tbody/tr[2]/td[2]/ul/li')
        DisplayR.append(displayr.text) #Scrape display resolution of the product
    except:
        DisplayR.append('-')
    time.sleep(2)
    try:
        processor = driver.find_element_by_xpath('/html/body/div[1]/div/div[3]/div[1]/div[2]/div[8]/div[4]/div/div[2]/div[1]/div[3]/table/tbody/tr[2]/td[2]/ul/li')
        Processor.append(processor.text) #Scrape processor of the product
    except:
        Processor.append('-')
    time.sleep(2)
    try:
        core = driver.find_element_by_xpath('/html/body/div[1]/div/div[3]/div[1]/div[2]/div[8]/div[4]/div/div[2]/div[1]/div[3]/table/tbody/tr[3]/td[2]/ul/li')
        Core.append(core.text)
    except:
        Core.append('-')
    time.sleep(2)
    try:
        battery = driver.find_element_by_xpath('/html/body/div[1]/div/div[3]/div[1]/div[2]/div[8]/div[4]/div/div[2]/div[1]/div[8]/table/tbody/tr/td[2]/ul/li')
        Battery.append(battery.text) #Scrape battery capacity of the product
    except:
        Battery.append('-')
    time.sleep(2)
    try:
        price = driver.find_element_by_xpath('/html/body/div[1]/div/div[3]/div[1]/div[2]/div[2]/div/div[4]/div[1]/div/div[1]')
        Price.append(price.text) #Scrape price of the product
    except:
        Price.append('-')

In [70]:
for i in Product_url:
    driver.get(i)
    try:
        brand = driver.find_element_by_xpath('/html/body/div[1]/div/div[3]/div[1]/div[2]/div[1]/div[1]/div/div[4]/a')
        Brand.append(brand.text)
    except:
        Brand.append('-')

In [80]:
dfm = pd.DataFrame() #Making dataframe
dfm['Brand'] = Brand
dfm['Product Name'] = Product
dfm['Colour'] = Colour
dfm['Ram'] = Ram
dfm['Storage(Rom)'] = Rom
dfm['Primary Camera'] = PCamera
dfm['Secondary Camera'] = SCamera
dfm['Display Size'] = DisplaySize  
dfm['Display Resolution'] = DisplayR
dfm['Processor'] = Processor
dfm['Processor Core'] = Core
dfm['Battery Capacity'] = Battery  
dfm['Price'] = Price
dfm['Product_url'] = Product_url
dfm.head()

,Brand,Product Name,Colour,Ram,Storage(Rom),Primary Camera,Secondary Camera,Display Size,Display Resolution,Processor,Processor Core,Battery Capacity,Price,Product_url
0,REDMI Mobiles,Note 10 Pro Max,Dark Night,6 GB,128 GB,108MP + 8MP + 5MP + 2MP,16MP Front Camera,16.94 cm (6.67 inch),2400 x 1080 Pixels,Qualcomm Snapdragon 732G,Octa Core,5020 mAh,"₹20,862",https://www.flipkart.com/redmi-note-10-pro-max...
1,REDMI Mobiles,Note 10 Pro Max,Dark Night,8 GB,128 GB,108MP + 8MP + 5MP + 2MP,16MP Front Camera,16.94 cm (6.67 inch),2400 x 1080 Pixels,Qualcomm Snapdragon 732G,Octa Core,5020 mAh,-,https://www.flipkart.com/redmi-note-10-pro-max...
2,REDMI Mobiles,Note 10 Pro Max,Glacial Blue,8 GB,128 GB,108MP + 8MP + 5MP + 2MP,16MP Front Camera,16.94 cm (6.67 inch),2400 x 1080 Pixels,Qualcomm Snapdragon 732G,Octa Core,5020 mAh,-,https://www.flipkart.com/redmi-note-10-pro-max...
3,REDMI Mobiles,Note 10 Pro Max,Vintage Bronze,8 GB,128 GB,108MP + 8MP + 5MP + 2MP,16MP Front Camera,16.94 cm (6.67 inch),2400 x 1080 Pixels,Qualcomm Snapdragon 732G,Octa Core,5020 mAh,-,https://www.flipkart.com/redmi-note-10-pro-max...
4,REDMI Mobiles,Note 10 Pro Max,Glacial Blue,6 GB,128 GB,108MP + 8MP + 5MP + 2MP,16MP Front Camera,16.94 cm (6.67 inch),2400 x 1080 Pixels,Qualcomm Snapdragon 732G,Octa Core,5020 mAh,"₹20,786",https://www.flipkart.com/redmi-note-10-pro-max...

# Write a program to scrap geospatial coordinates (latitude, longitude) of a city searched on google maps

In [137]:
page4 = driver.get('https://www.google.com/maps')

In [138]:
city_search = driver.find_element_by_id("searchboxinput")
city_search.send_keys('Pune')

btn = driver.find_element_by_id("searchbox-searchbutton")
btn.click()

In [154]:
Latitude = []
Longitude = []
latitude = driver.find_element_by_xpath('/html/body/jsl/div[3]/div[10]/div[8]/div/div[1]/div/div/div[2]/div[1]/div[1]/h2')
Latitude.append(latitude.text.replace('18.518986, ',''))
Longitude.append(latitude.text.replace('73.855641',''))

In [155]:
dfe  =pd.DataFrame()
dfe['City'] = ['Pune']
dfe['Longitude'] = Longitude
dfe['Latitude'] = Latitude
dfe

   City    Longitude   Latitude
0  Pune  18.518986,   73.855641

# Write a program to scrap all the available details of best gaming laptops from digit.in.

In [ ]:
#Setting up firefox web-driver
driver = webdriver.Firefox(executable_path = 'geckodriver.exe')
page6 = driver.get('https://www.digit.in/')

In [123]:
driver.find_element_by_xpath('/html/body/div[1]/div/div[4]/ul/li[3]/a').click()

In [124]:
driver.find_element_by_xpath('/html/body/div[6]/div/div[2]/div[2]/ul/li[10]/a').click()

In [135]:
url = driver.find_elements_by_xpath('//div[@class="TopNumbeHeading sticky-footer"]//a')
product_url = []#empty List

for i in url:
    product_url.append(i.get_attribute('href'))

OS = []#empty List
Display = []#empty List
Processor = []#empty List
Memory = []#empty List

for i in product_url:
    driver.get(i)
    try:
        os = driver.find_element_by_xpath('/html/body/div[3]/div[2]/div[3]/div[3]/div[3]/div/ul/li[1]/div/p[2]/strong ')
        Os.append(os.text)
    except:
        OS.append('-')
    time.sleep(2)
    try:
        dispaly = driver.find_element_by_xpath('/html/body/div[3]/div[2]/div[3]/div[3]/div[3]/div/ul/li[2]/div/p[2]/strong')
        Display.append(display.text)
    except:
        Display.append('-')
    time.sleep(2)
    try:
        processor = driver.find_element_by_xpath('//*[@id="overview"]/div[3]/div[3]/div/ul/li[3]/div/p[2]/strong')
        Processor.append(processor.text)
    except:
        Processor.append('-')
    time.sleep(2)
    try:
        memory = driver.find_element_by_xpath('/html/body/div[3]/div[2]/div[3]/div[3]/div[3]/div/ul/li[4]/div/p[2]/strong')
        Memory.append(memory.text)
    except:
        Memory.append('-')

In [136]:
dfl = pd.DataFrame()
dfl['OS'] = OS  
dfl['Display'] = Display  
dfl['Processor'] = Processor  
dfl['Memory'] = Memory  
dfl

,OS,Display,Processor,Memory
0,-,-,10th Generation Intel® Core™ I7-10700 | 2.90 GHz,1 TB SSD/16 GBGB DDR4
1,-,-,-,-
2,-,-,AMD 3rd Generation Ryzen 9 | 3.3 GHz,1 TB SSD/16 GBGB DDR4
3,-,-,10th Generation Intel® Core™ I5-10300H | 2.50 GHz,1 TB SSD/16 GBGB DDR4
4,-,-,Intel Core I7 10th Gen 10875H | NA,512 GB SSD/4 GBGB DDR4
5,-,-,AMD Ryzen™ 5-5500U Hexa-core | NA,512 GB SSD/8 GBGB DDR4

# Write a python program to scrape the details for all billionaires from www.forbes.com. Details to be scrapped: “Rank”, “Name”, “Net worth”, “Age”, “Citizenship”, “Source”, “Industry”.

In [32]:
page7 = driver.get('https://www.forbes.com/')

In [33]:
driver.find_element_by_xpath('//button[@class="icon--hamburger"]').click()

In [66]:
Rank = []#empty List
Name = []#empty List
Net_worth = []#empty List
Age = []#empty List
Citizenship = []#empty List
Source = []#empty List
Industry = []#empty List

rank = driver.find_elements_by_xpath('//div[@class="rank"]')
name = driver.find_elements_by_xpath('//div[@class="personName"]')
net = driver.find_elements_by_xpath('//div[@class="netWorth"]')
age = driver.find_elements_by_xpath('//div[@class="age"]')
citizen = driver.find_elements_by_xpath('//div[@class="countryOfCitizenship"]')
source = driver.find_elements_by_xpath('//div[@class="source-column"]')
industry = driver.find_elements_by_xpath('//div[@class="category"]')

for i in rank:
    Rank.append(i.text)
time.sleep(2) #Scrape rank

for i in name:
    Name.append(i.text)#Scrape name 
time.sleep(2)

for i in net:
    Net_worth.append(i.text)#Scrape networth
time.sleep(2)

for i in age:
    Age.append(i.text)#Scrape Age
time.sleep(2)

for i in citizen:
    Citizenship.append(i.text)#Scrape citizenship
time.sleep(2)

for i in source:
    Source.append(i.text)#Scrap Source
time.sleep(2)

for i in industry:
    Industry.append(i.text)
time.sleep(2)#Scrape Industry

In [74]:
driver.find_element_by_xpath('/html/body/div[1]/div[1]/div/div/div[3]/div[2]/div[2]/div[2]/div[27]/div[7]/div[2]/button[2]/div/i').click()

In [75]:
rank = driver.find_elements_by_xpath('//div[@class="rank"]')
name = driver.find_elements_by_xpath('//div[@class="personName"]')
net = driver.find_elements_by_xpath('//div[@class="netWorth"]')
age = driver.find_elements_by_xpath('//div[@class="age"]')
citizen = driver.find_elements_by_xpath('//div[@class="countryOfCitizenship"]')
source = driver.find_elements_by_xpath('//div[@class="source-column"]')
industry = driver.find_elements_by_xpath('//div[@class="category"]')

for i in rank:
    Rank.append(i.text)
time.sleep(2)

for i in name:
    Name.append(i.text)
time.sleep(2)

for i in net:
    Net_worth.append(i.text)
time.sleep(2)

for i in age:
    Age.append(i.text)
time.sleep(2)

for i in citizen:
    Citizenship.append(i.text)
time.sleep(2)

for i in source:
    Source.append(i.text)
time.sleep(2)

for i in industry:
    Industry.append(i.text)
time.sleep(2)

driver.find_element_by_xpath('/html/body/div[1]/div[1]/div/div/div[3]/div[2]/div[2]/div[2]/div[27]/div[7]/div[2]/button[2]/div/i').click()

time.sleep(5)

rank = driver.find_elements_by_xpath('//div[@class="rank"]')
name = driver.find_elements_by_xpath('//div[@class="personName"]')
net = driver.find_elements_by_xpath('//div[@class="netWorth"]')
age = driver.find_elements_by_xpath('//div[@class="age"]')
citizen = driver.find_elements_by_xpath('//div[@class="countryOfCitizenship"]')
source = driver.find_elements_by_xpath('//div[@class="source-column"]')
industry = driver.find_elements_by_xpath('//div[@class="category"]')

for i in rank:
    Rank.append(i.text)
time.sleep(2)

for i in name:
    Name.append(i.text)
time.sleep(2)

for i in net:
    Net_worth.append(i.text)
time.sleep(2)

for i in age:
    Age.append(i.text)
time.sleep(2)

for i in citizen:
    Citizenship.append(i.text)
time.sleep(2)

for i in source:
    Source.append(i.text)
time.sleep(2)

for i in industry:
    Industry.append(i.text)
time.sleep(2)

In [78]:
dff = pd.DataFrame() #Making DataFrame
dff['Rank']= Rank  
dff['Name']=Name  
dff['Net_worth']=Net_worth  
dff['Age']=Age  
dff['Citizenship']=Citizenship  
dff['Source']=Source  
dff['Industry']=Industry

dff

,Rank,Name,Net_worth,Age,Citizenship,Source,Industry
0,1.,Jeff Bezos,$177 B,57,United States,Amazon,Technology
1,2.,Elon Musk,$151 B,49,United States,"Tesla, SpaceX",Automotive
2,3.,Bernard Arnault & family,$150 B,72,France,LVMH,Fashion & Retail
3,4.,Bill Gates,$124 B,65,United States,Microsoft,Technology
4,5.,Mark Zuckerberg,$97 B,36,United States,Facebook,Technology
...,...,...,...,...,...,...,...
595,589.,Lin Shu-hong,$4.8 B,92,Taiwan,petrochemicals,Manufacturing
596,589.,Yuri Milner,$4.8 B,59,Israel,tech investments,Finance & Investments
597,589.,Issad Rebrab & family,$4.8 B,77,Algeria,food,Food & Beverage
598,589.,Thomas Schmidheiny,$4.8 B,75,Switzerland,cement,Construction & Engineering
599,589.,Chairul Tanjung,$4.8 B,58,Indonesia,diversified,Diversified

In [80]:
dff.to_csv('Forbes Billionaire List.csv', index = False)

# Write a program to extract at least 500 Comments, Comment upvote and time when comment was posted from any YouTube Video.

In [8]:
driver = webdriver.Firefox(executable_path = 'geckodriver.exe')
page8 = driver.get('https://www.youtube.com/')

In [10]:
driver.find_element_by_xpath('//input[@class="ytd-searchbox"]').send_keys('gangnam style')
driver.find_element_by_xpath('//button[@class="style-scope ytd-searchbox"]').click()

In [11]:
driver.find_element_by_xpath('//a[@class="yt-simple-endpoint style-scope ytd-video-renderer"]').click()

In [20]:
Comments = []#empty list
Comments_upvote = []#empty list
Time = []#empty list

try:
    comments = driver.find_elements_by_xpath('//*[@id="content-text"]')
    for i in comments:
        Comments.append(i.text) #Scraping Comments
except:
    Comments.append('-')
    time.sleep(3)
try:
    comments_upvote = driver.find_elements_by_xpath('//*[@id="vote-count-middle"]')
    for i in comments_upvote:
        Comments_upvote.append(i.text) #Scraping Comments Upvote
except:
    Comments_upvote.append('-')
    time.sleep(3)
try:
    time = driver.find_elements_by_xpath('//*[@id="header-author"]/yt-formatted-string/a')
    for i in time:
        Time.append(i.text.replace('(edited)','')) #Scrape posted time
except:
    Time.append('-')

In [21]:
#Making DataFrame
dfy = pd.DataFrame()
dfy['Comments'] = Comments
dfy['Comments_upvote'] = Comments_upvote
dfy['Time'] = Time

dfy

,Comments,Comments_upvote,Time
0,This guy technically ruled the world for a time,208K,1 year ago
1,The track that broke YouTube's view counter an...,1.1K,1 day ago
2,Didn't realize we have been listening to kpop ...,140K,1 year ago
3,Who came here because this randomly crossed yo...,442K,1 year ago
4,Bruh 8 years later and people are still listen...,100K,1 year ago
...,...,...,...
589,We bring it the Moon Baby 🚀🚀🚀🙌💎,225,3 months ago
590,No kpop group can beat this song,1,2 days ago
591,This will be the MOASS anthem...💎👐🦍💎👐🦍💎👐🦍,30,1 week ago
592,Hələdə qulağ asan var bu mahniya,1,1 day ago
593,Like: Gangnam style\n\nComment: Despacito😕😷,63K,1 year ago

In [22]:
dfy.to_csv('Ganganam_Style_Comments.csv', index = False)

#  Write a python program to scrape a data for all available Hostels from https://www.hostelworld.com/ in “London” location. 
## You have to scrape hostel name, distance from city centre, ratings, total reviews, overall reviews, privates from price, dorms from price, facilities and property description.

In [156]:
driver = webdriver.Firefox(executable_path = 'geckodriver.exe')
page8 = driver.get('https://www.hostelworld.com/')

In [157]:
driver.find_element_by_xpath('//*[@id="search-input-field"]').send_keys('London')

In [160]:
driver.find_element_by_xpath('/html/body/div[1]/div/div/div[1]/div[1]/div/div[2]/div[4]/div/div[2]/div/div[1]/div/div/ul/li[2]').click()
driver.find_element_by_xpath('//*[@id="search-button"]').click()

In [161]:
Hostel_url = []#empty list
Name = []#empty list
Distance = []#empty list
Rating = []#empty list
Reviews = []#empty list
PrivatesFromPrice = []#empty list
DormsFromPrice = []#empty list
Facilities = []#empty list
Description = []#empty list

url = driver.find_elements_by_xpath('//h2[@class="title title-6"]//a')
for i in url:
    Hostel_url.append(i.get_attribute('href')) #Scrape url's
time.sleep(2)

name = driver.find_elements_by_xpath('//h2[@class="title title-6"]')
for i in name:
    Name.append(i.text) #Scrape hostel name
time.sleep(2)

distance  = driver.find_elements_by_xpath('//a[@class="show-on-map"]//span[1]')
for i in distance:
    Distance.append(i.text) #Scrape Distance
time.sleep(2)

try:
    rating = driver.find_elements_by_xpath('div[@class="score orange big"]')
    for i in  rating:
        Rating.append(i.text) #Scrape Ratings
try:
    rating1 = driver.find_elements_by_xpath('//div[@class="score gray big"]')
    for i in rating1:
        Rating.append(i.text)
except:
    Rating.append('-')
time.sleep(2)

reviews = driver.find_elements_by_xpath('//div[@class="reviews"]')
for i in reviews:
    Reviews.append(i.text.replace('Total Reviews','').strip()) #Scrape Reviews
time.sleep(2)

Info = []
info = driver.find_elements_by_xpath('//div[@class="price-col"]')
for i in info:
    Info.append(i.text.replace('Dorms From\n','').replace('Privates From\n',''))
time.sleep(2)
for i in range(0,len(Info),2):
    PrivatesFromPrice.append(Info[i])
time.sleep(2)

for i in range(1,len(info),2):
    DormsFromPrice.append(Info[i]) #Scraping Price
time.sleep(2)

try:
    facilities = driver.find_elements_by_xpath('//div[@class="facilities-label facilities"]')
    for i in facilities:
        Facilities.append(i.text.replace('\n',',')) #Scraping Facilities
except:
    Facilities.append('-')
time.sleep(2)  

for i in Hostel_url:
    driver.get(i)
    try:
        desc = driver.find_elements_by_xpath('//*[@id="__layout"]/div/div[1]/section/div[6]/div/div[2]/div/div/div[2]')
        Description.append(i.text)#Scraping Description
    except:
        Description.append('-')
        time.sleep(2)

In [199]:
#Making DataFrame
dfh = pd.DataFrame()
dfh['Name'] = Name  
dfh['Distance'] = Distance    
dfh['Reviews'] = Reviews  
dfh['PrivatesFromPrice'] = PrivatesFromPrice  
dfh['DormsFromPrice'] = DormsFromPrice  
dfh['Facilities'] = Facilities  
dfh['Description'] = Description  
dfh

,Name,Distance,Reviews,PrivatesFromPrice,DormsFromPrice,Facilities,Description
0,London Waterloo Hostel,Hostel - 0.7km from city centre,2409,No Privates Available,Rs1460,"Free WiFi,Free Breakfast,Follows Covid-19 sani...",-
1,Barmy Badger Backpackers,Hostel - 5.5km from city centre,1653,No Privates Available,Rs2129,"Free WiFi,Free Breakfast",-
2,Wombat's The City Hostel London,Hostel - 3.6km from city centre,13143,Rs8232,Rs1874,"Free WiFi,Follows Covid-19 sanitation guidance",-
3,Prime Backpackers Angel,Hostel - 3.6km from city centre,513,No Privates Available,Rs2398,"Free WiFi,Follows Covid-19 sanitation guidance",-
4,St Christopher's Village,Hostel - 1.8km from city centre,10830,Rs6082,Rs1358,"Free WiFi,Follows Covid-19 sanitation guidance",-
5,"PubLove @ The Steam Engine, Waterloo",Hostel - 0.5km from city centre,190,No Privates Available,Rs1520,"Free WiFi,Follows Covid-19 sanitation guidance",-
6,"PubLove @ The Crown, Battersea",Hostel - 4.7km from city centre,208,Rs8612,Rs1520,"Free WiFi,Follows Covid-19 sanitation guidance",-
7,Safestay London Elephant & Castle,Hostel - 1.7km from city centre,3952,Rs5473,Rs1824,"Free WiFi,Follows Covid-19 sanitation guidance",-
8,Urbany Hostel London,Hostel - 5.4km from city centre,106,Rs4332,Rs1764,"Free WiFi,Follows Covid-19 sanitation guidance",-
9,"PubLove @ The Green Man, Paddington",Hostel - 4.3km from city centre,392,Rs10646,Rs1520,"Free WiFi,Follows Covid-19 sanitation guidance",-
10,Well Street Hall,Bed and Breakfast - 6.7km from city centre,0,Rs4257,No Dorms Available,"Free WiFi,Free Breakfast,Follows Covid-19 sani...",-
11,Mornington Camden,Hostel - 4.1km from city centre,41,No Privates Available,Rs3178,Free WiFi,-
12,PubLove @ The Rose & Crown,Hostel - 1.6km from city centre,99,No Privates Available,Rs1520,"Free WiFi,Follows Covid-19 sanitation guidance",-
13,New Cross Inn Hostel,Hostel - 6.1km from city centre,1005,Rs3120,Rs1213,"Free WiFi,Free Breakfast",-
14,Strand Continental,Hostel - 1.3km from city centre,773,Rs4561,Rs1916,"Free Breakfast,Follows Covid-19 sanitation gui...",-
15,St Christopher's Oasis-Female Only,Hostel - 1.8km from city centre,594,No Privates Available,Rs1443,"Free WiFi,Follows Covid-19 sanitation guidance",-
16,Astor Museum Inn,Hostel - 2.2km from city centre,8714,No Privates Available,Rs1723,"Free WiFi,Follows Covid-19 sanitation guidance",-
17,Astor Kensington,Hostel - 4.9km from city centre,6326,Rs7095,Rs1419,"Free WiFi,Follows Covid-19 sanitation guidance",-
18,Mapesbury Hostel,Hostel - 8.2km from city centre,357,Rs4561,No Dorms Available,"Free WiFi,Follows Covid-19 sanitation guidance",-
19,Hootananny Hostel,Hostel - 5km from city centre,1406,No Privates Available,Rs1637,"Free WiFi,Free Breakfast",-
20,Astor Hyde Park,Hostel - 4.3km from city centre,11326,No Privates Available,Rs1419,"Free WiFi,Follows Covid-19 sanitation guidance",-
21,Phoenix Hostel,Hostel - 4.2km from city centre,3421,Rs2220,Rs1581,Free WiFi,-
22,247london Hostel and Private Rooms,Hostel - 8.2km from city centre,443,Rs5169,No Dorms Available,Free WiFi,-
23,Burlington Residence,Hostel - 7.1km from city centre,26,No Privates Available,Rs2068,"Free WiFi,Free Breakfast,Follows Covid-19 sani...",-
24,SoHostel,Hostel - 2km from city centre,3961,No Privates Available,Rs2027,"Free WiFi,Follows Covid-19 sanitation guidance",-
25,Clink261,Hostel - 3.2km from city centre,3172,No Privates Available,Rs1335,"Free WiFi,Follows Covid-19 sanitation guidance",-
26,Generator London,Hostel - 3km from city centre,6737,Rs8007,Rs1926,"Free WiFi,Follows Covid-19 sanitation guidance",-
27,"PubLove @ The White Ferry, Victoria",Hostel - 2.4km from city centre,134,No Privates Available,Rs1520,"Free WiFi,Follows Covid-19 sanitation guidance",-
28,Smart Russell Square Hostel,Hostel - 2.6km from city centre,9504,No Privates Available,Rs1161,"Free WiFi,Follows Covid-19 sanitation guidance",-
29,Keystone House Kings Cross,Hostel - 3.5km from city centre,8111,Rs4221,No Dorms Available,Free WiFi,-